service:
  publicurl: "__VIKUNJA_SERVICE_PUBLICURL__"

auth:
  openid:
    enabled: true
    providers:
      authentik:
        name: authentik
        authurl: "__VIKUNJA_OIDC_AUTH_URL__"
        clientid: "__VIKUNJA_OIDC_CLIENT_ID__"
        clientsecret: "__VIKUNJA_OIDC_CLIENT_SECRET__"
